export const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: "Carolux Insulation LLC",
  description:
    "Owner-operated insulation company serving Charlotte & Gastonia, NC. Blown-in attic insulation and crawl space vapor barriers.",
  url: "https://caroluxinsulation.com",
  telephone: "+17042282729",
  email: "team@caroluxinsulation.com",
  areaServed: [
    "Charlotte, NC",
    "Gastonia, NC",
    "Huntersville, NC",
    "Pineville, NC",
    "Concord, NC",
    "Harrisburg, NC",
    "Belmont, NC",
    "Cramerton, NC",
    "Lowell, NC",
    "Mount Holly, NC",
    "Stanley, NC",
    "Matthews, NC",
    "Mint Hill, NC",
  ],
  priceRange: "$$",
  sameAs: ["https://instagram.com/caroluxinsulation"],
};
